// <auto-generated />
namespace TheCars.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removeenginetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeenginetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712301343218_removeenginetable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
